---
title: "За проекта"
---

```{python}
#| label: libraries
import pandas as pd
```

## Голямото защо?

Този сайт е създаден през 2024 г. Целта му е да бъде в помощ на всеки, който се интересува от работата на публичната администрация и качеството на административно обслужване в Република България.

Данните в него са официални и публични, получени от ИИСДА[^1], периодично кабинетно проучване на интернет страниците на администрациите, както и техните отговори на заявления по реда на ЗДОИ[^2].

[^1]: Интегрирана информационна система на държавната администрация - <https://iisda.government.bg/>

[^2]: Закон за достъп до обществена информация

## Представяне на данните

Изследванията в сайта се представят съгласно разпределението на администрациите по вид:

```{python}
administracii = pd.read_csv("data/V.A.11.2020-2023.csv")
```

### Видове администрации на изпълнителната власт

```{python}
for number, letter in enumerate(administracii['Вид администрация на изпълнителната власт'].unique()): 
    print(number + 1, '. ', letter)
```

### Видове административни структури

```{python}
for number, letter in enumerate(administracii['Вид административна структура'].unique()): 
    print(number + 1, '. ', letter)
```


## Периоди на изследване

::: callout-tip
## Важно

Данните за отделните администрации се представят и по години. А на страниците за обобщени доклади се анализира информацията за различни времеви периоди.
:::

## За автора

Автор на сайта е Ивайло Спасов Спасов. Чрез създаването на този публичен ресурс той надгражда резултатите, получени при изследването, направено към дипломната му работа[^3] за придобиване на магистърска степен по "Публичен мениджмънт и политики" в Софийски университет "Св. Климент Охридски" през 2023 г.

Авторът подкрепя отворената наука и полага усилия данните и изчисленията в изследванията да са публично достъпни и с възможност за повтаряне.

[^3]: "Измерване удовлетвореността на потребителите от услугите на териториалните администрации в Област Пловдив". Период на изследването 2020 - 2022 г.
