---
title: "Развитие предлагането на административните услуги по електронен път от областните администрации в периода 2020 - 2023 г."
format: html
---

```{python}
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
```

```{python}
# label: load-data
obl_adm = pd.read_csv('../data/V.A.11.2020-2023.csv')
```

## Въведение

### Цел на изследването

Целта на изследването е да проследи развитието на нормативната база за предоставяне на административни услуги по електронен път и нейното практическо приложение в аспекта на повишаване популярността на електронното заявяване и получаване на административни услуги сред физическите и юридическите лица.

### Предмет на изследването

### Обект на изследването

### Обхват на изследването

Изследването обхваща административните услуги на областните администрации, предоставени по електронен път в периода 2020 - 2023 г. (включително).

### Задачи на изследването

Задачите на изследването са:

1.  Да установи методите за отчитане на административните услуги, заявяни и предоставени по електронен път;
2.  Да установи трудностите при отчитане на административните услуги, заявяни и предоставени по електронен път;
3.  Да проучи и установи политиките, които прилагат изследваните администрации, за популяризиране на административните услуги, предоставяни по електронен път;
4.  Да регистрира вазимовръзка (ако такава съществува) между предоставянето на дадена административна услуга в по-висока степен по електронен път и повишаване на търсенето ѝ.

### Основен изследователски проблем

### Хипотеза

Липсата на стандарт в изискванията за регистрация на административните услуги, заявени и изпълнени по електронен път, поражда трудности при отчитането и анализирането на резултатите от политиките по тяхното популяризиране. Изследваните администрации полагат недостатъчни усилия да популяризират заявяването и изпълнението на услугите по електронен път и предимствата за гражданите от това.

### Методи на изследването

При реализация на изследването са използвани следните методи:

1.  Кабинетно проучване на съществуващата нормативна база, отнасяща се до административните услуги предоставяни по електронен път;

2.  Експертен анализ на данните, публично предоставени в интернет страницата на ИИСДА;

3.  Събиране на информация по реда на Закона за достъп до обществена информация;

4.  Емпирично проучване в изследваните администрации.

## Изложение

### Информация за услугите

### Публично достъпни данни за предоставени услуги по електронен път

```{python}
nAeServices = 0 # Липсващи данни за брой електронни услуги
nAServices = 0  # Липсващи данни за брой административни услуги
allRows = 0     # Колко са всички редове на таблицата
```

Общ брой непредоставени данни за електронни услуги е `{python} nAeServices`.

Общ брой непредоставени данни за услуги е `{python} nAServices`.

Общ брой редове `{python} allRows`.

### Въпросници

#### Въпросник за областната администрация

1.  

#### Въпросник за физически лица

1.  Бихте ли предпочели да заявите настоящата административна услуга по електронен път, вместо да посещавате Областната администрация?

2.  Информирахте ли се предварително дали заявяването на настоящата услуга може да бъде осъществено по електронен път?

3.  Когато заявихте услугата, бяхте ли информиран/а, че тя може да се заяви и изпълни по електронен път

#### Въпросник за юридически лица

## Източници

Закон за администрацията

Закон за електронното управление

НАРЕДБА за общите изисквания към информационните системи, регистрите и електронните административни услуги

Наръчник за прилагане на Методология за усъвършенстване на работните процеси за предоставяне на административни услуги

Подаване_приемане_изпращане_и_съхраняване_на_електронни_документи.doc

Предоставяне_на_електронни_административни_услуги.doc